### ISSUE TITLE
Timestamp数据类型不支持吗？

### ISSUE THREAD

**Issue by richsleo** [jsonzou/jmockdata#11]
Timestamp数据类型不支持？

**Comment by jsonzoup** [comment]
你好，暂时没有支持，但是提供了自己可扩展的接口。
比如：
第一步：新建mocker类
public class TimestampMocker implements Mocker<Timestamp >{
     @Override
  public Timestamp mock(MockConfig mockConfig) {
      // 这里写你的mocker计算逻辑
    return  timestamp;
  }
}
第二部：注册mocker类
new MockConfig().registerMocker(TimestampMocker.class,Timestamp.class)

以上就可以了。希望可以帮到你。

**Comment by jsonzoup** [comment]
你好，暂时没有支持，但是提供了自己可扩展的接口。
比如：
第一步：新建mocker类
public class TimestampMocker implements Mocker{
@override
public Timestamp mock(MockConfig mockConfig) {
// 这里写你的mocker计算逻辑
return timestamp;
}
}
第二部：注册mocker类
new MockConfig().registerMocker(TimestampMocker.class,Timestamp.class)

以上就可以了。希望可以帮到你。

**Comment by jsonzoup** [comment]
新版本已支持
https://github.com/jsonzou/jmockdata/releases/tag/jmockdata-4.2.0-RELEASE
