### ISSUE TITLE
JDK8枚举报错Field field = clazz.getDeclaredField("$VALUES");

### ISSUE THREAD

**Issue by zhanglei-1987** [jsonzou/jmockdata#14]
Enum[] enums = mockConfig.getcacheEnum(clazz.getName());
    if (enums == null) {
      try {
        Field field = clazz.getDeclaredField("$VALUES");
        field.setAccessible(true);
        enums = (Enum[]) field.get(clazz);
        if (enums.length == 0) {
          throw new MockException("空的enum不能模拟");
        }
        mockConfig.cacheEnum(clazz.getName(), enums);
      } catch (NoSuchFieldException | IllegalAccessException e) {
        throw new MockException(e);
      }
    }
    return (T) enums[RandomUtils.nextInt(0, enums.length)];
  }

**Comment by jsonzoup** [comment]
方便的话，可以看一下具体的代码吗。谢谢。

**Comment by jsonzoup** [comment]
jmockata-4.0.0 released
