### ISSUE TITLE
MapMocker 数组下标越界bug 

### ISSUE THREAD

**Issue by huxingnan** [jsonzou/jmockdata#15]
com.github.jsonzou.jmockdata.mocker.MapMocker#mock
line:25 ,存在java.lang.ArrayIndexOutOfBoundsException: 异常。

bug 复现：
@Test
    public  void  testMockData (){
//当 mock Map 类型时 不指定 泛型类型 ，会出现 数组下标越界问题
        Map mock = JMockData.mock(Map.class);
        System.out.println(JSON.toJSONString(mock));
    }

**Comment by jsonzoup** [comment]
收到。最近计划做个升级。

**Comment by jsonzoup** [comment]
泛型模拟正确用法：
JMockData.mock(new TypeReference<Map<String,String>(){})
