### ISSUE TITLE
没有域的对象会报数组越界

### ISSUE THREAD

**Issue by luoGit** [jsonzou/jmockdata#21]
如果存在某个对象，没有成员变量，对这个对象进行Mock的时候会抛数组越界

**Comment by jsonzoup** [comment]
你好请问你用的哪个版本？
我测试了一下是没有问题的，也请把你的代码贴出来我看看。

**Comment by luoGit** [comment]
用的最新版本，上次描述有误，是继承自ArrayList的子类，会产生ArrayIndexOutOfBoundsException

![image](https://user-images.githubusercontent.com/20441567/54405965-38898c80-4713-11e9-9b2a-375a8e18c32c.png)

![image](https://user-images.githubusercontent.com/20441567/54405981-463f1200-4713-11e9-986f-1799d9649e10.png)

**Comment by jsonzoup** [comment]
这个暂时无法支持自定义的List.
你可以自定义mock类型注册进去。
参考：
MockConfig mockConfig = new MockConfig()
            .registerMocker(Mocker mocker, Class<T>... clazzs)
