### ISSUE TITLE
发现2个问题，一起提下

### ISSUE THREAD

**Issue by CodingOX** [jsonzou/jmockdata#26]
1. 不支持Java8的 LocalDateTime
2. 如果实体类有Lombok的Accessor ，那么也无法正确生成模拟数据。
谢谢作者的好东西！

**Comment by jsonzoup** [comment]
1.有人提过，因为现在支持到jdk7所以LocalDateTime暂时还不支持。
2.模拟数据的bean请确保含有getter,setter方法
