### ISSUE TITLE
泛型多层嵌套bug

### ISSUE THREAD

**Issue by luckyQing** [jsonzou/jmockdata#27]
泛型多层嵌套bug

**Comment by jsonzoup** [comment]
兄弟，可不可以吧代码和报错的异常栈贴出来。

**Comment by luckyQing** [comment]
不要了，我找了一个更加强大的mock开源库，稍微自己修改了一下，支持多层嵌套泛型。功能强大到我自己都不敢相信，哈哈哈

**Comment by luckyQing** [comment]
https://github.com/mtedone/podam
