### ISSUE TITLE
希望支持lombok框架

### ISSUE THREAD

**Issue by SYZ1421** [jsonzou/jmockdata#35]
现在lombok框架使用挺广泛的, 希望支持一下.

**Comment by jsonzoup** [comment]
lombok下模拟不出来？

**Comment by SYZ1421** [comment]
是的, 刚测试必须生成set方法才可以.

**Comment by jsonzoup** [comment]
lombok生成是支持的。你看源码测试包下有关于lombok bean的测试。
不知你是怎么写的？你方便贴出来你的代码吗？

**Comment by SYZ1421** [comment]
查了下, 是因为使用了这个注解导致的: @lombok.experimental.Accessors(chain = true)
这个注解使set方法返回this而非void, 以支持链式操作, 导致ReflectionUtils.fieldAndSetterMethod拿不到WriteMethod导致的.
