### ISSUE TITLE
4.1.2版本无法处理[a-z][A-Z][0-9]这种匹配规则

### ISSUE THREAD

**Issue by WhyXLF** [jsonzou/jmockdata#36]
在UserDefinedLetterPickerScanner的scan方法中没有把"-"加入到bounds中，导致RandomLetterPicker的constructByCharacterRange方法无法识别到"-"进而跳过了处理[a-z][A-Z][0-9]这种匹配规则，希望能尽快修复一下~
![image](https://user-images.githubusercontent.com/10573541/72040433-7b8ca000-32e3-11ea-8c4f-f120559e9e7b.png)

![image](https://user-images.githubusercontent.com/10573541/72040379-5ac44a80-32e3-11ea-83b2-b86d2ca8edff.png)

**Comment by jsonzoup** [comment]
你好，是可以的，请问你具体的使用场景是什么，方便把代码贴出来吗？

**Comment by WhyXLF** [comment]
> 你好，是可以的，请问你具体的使用场景是什么，方便把代码贴出来吗？

如下图，因为没有了“-”，所以导致正则变成了“[AZ]”
![image](https://user-images.githubusercontent.com/10573541/72077158-bcaba100-3331-11ea-9d69-795c01f9c16c.png)

**Comment by Zhujinyong** [comment]
> 你好，是可以的，请问你具体的使用场景是什么，方便把代码贴出来吗？

version:4.1.2 ，我也是这样，希望尽快解决一下

**Comment by jsonzoup** [comment]
确实有bug，近期上一个修复版本

**Comment by jsonzoup** [comment]
新版本已修复
https://github.com/jsonzou/jmockdata/releases/tag/jmockdata-4.2.0-RELEASE
