### ISSUE TITLE
建议新增一个比较使用的功能

### ISSUE THREAD

**Issue by rootpophome** [jsonzou/jmockdata#37]
getDataConfig(***,fieldName)
获取到字段
** 相关建议:
1. 用本地代码赋值对字段赋值
** 使用场景:
1. 必须使用公司创建流水号工具生成流水号,流水号生成规则无法使用正则表达式明确
2. 某一个字段必须使用规定值

**Comment by jsonzoup** [comment]
4.3已支持通过beanmocker拦截器自定义生成规则
