### ISSUE TITLE
java.time.LocalDateTime 引发APP崩溃

### ISSUE THREAD

**Issue by HeroBarry** [jsonzou/jmockdata#47]
Caused by: java.lang.ClassNotFoundException: Didn't find class "java.time.LocalDateTime" on path: DexPathList[[zip file 

最新版适配了java.time.LocalDateTime
但是低版本的jdk不支持

是否切换到上一个版本就能解决问题呢

**Comment by HeroBarry** [comment]
修改源码之后可以运行了 


`
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * 反射工具类
 */
public final class ReflectionUtils {

  private static ConcurrentHashMap<Class<?>, List<Field>> fieldCache = new ConcurrentHashMap<>();
  private static ConcurrentHashMap<Class<?>, List<Method>> methodCache = new ConcurrentHashMap<>();

  private ReflectionUtils() {
  }

  /**
   * 反射设置值
   *
   * @param object 对象
   * @param method 方法
   * @param args 方法参数对象
   * @throws ReflectiveOperationException 反射操作异常
   */
  public static void setRefValue(Object object, Method method, Object... args) throws ReflectiveOperationException {
    method.invoke(object, args);
  }

  /**
   * 反射设置值
   *
   * @param object 对象
   * @param field 属性
   * @param value 属性值
   * @throws ReflectiveOperationException 反射操作异常
   */
  public static void setFieldValue(Object object, Field field, Object value) throws IllegalAccessException {
    field.setAccessible(true);
    field.set(object, value);
  }

  /**
   * 获取全部属性
   * @param clazz
   * @return
   */
  public static List<Field> getFields(Class<?> clazz) {
    List<Field> fields = fieldCache.get(clazz);

    if (fields == null) {
      fields = new ArrayList<>();
      Class<?> superClass = clazz;
      while (superClass != Object.class) {
        List<Field> fieldList=new ArrayList<>();

        for (Field field:superClass.getDeclaredFields()){
          if (!field.toString().contains(" static ")){

            fieldList.add(field);
          }
        }

        fields.addAll(fieldList);
        superClass = superClass.getSuperclass();
      }
      fieldCache.put(clazz, fields);
    }
    return fields;
  }

  /**
   * 获取全部方法
   * @param clazz
   * @return
   */
  public static List<Method> getMethods(Class<?> clazz) {
    List<Method> methods = methodCache.get(clazz);

    if (methods == null) {
      methods = new ArrayList<>();
      Class<?> superClass = clazz;
      while (superClass != Object.class) {
        methods.addAll(Arrays.asList(superClass.getDeclaredMethods()));
        superClass = superClass.getSuperclass();
      }
      methodCache.put(clazz, methods);
    }
    return methods;
  }


  /**
   * 有setter方法的字段及其setter方法
   *
   * @param clazz Class对象
   * @return 有setter方法的 字段及其setter方法
   */
  public static Map<Field, Method> fieldAndSetterMethod(Class clazz) {

    Map<Field, Method> map = new LinkedHashMap<>();

    List<Field> fields =getFields(clazz);
    List<Method> methods =getMethods(clazz);

    for (Field field:fields){

      for (Method method:methods){
        if (method.getName().toLowerCase().equals("set"+field.getName().toLowerCase())){
          map.put(field,method);
        }
      }
    }

    return map;
  }

}
`

在Android设备上
`  @RequiresApi(api = Build.VERSION_CODES.O)
  private static final LocalDateTimeMocker LOCAL_DATE_TIME_MOCKER = new LocalDateTimeMocker();

  @RequiresApi(api = Build.VERSION_CODES.O)
  private static final LocalDateMocker LOCAL_DATE_MOCKER = new LocalDateMocker();

  @RequiresApi(api = Build.VERSION_CODES.O)
  private static final LocalTimeMocker LOCAL_TIME_MOCKER = new LocalTimeMocker();

  @RequiresApi(api = Build.VERSION_CODES.O)
  private static final TimestampMocker TIMESTAMP_MOCKER = new TimestampMocker();
  private boolean enabledCircle=false;`

后面出一个Android版就完美了

**Comment by jsonzoup** [comment]
上个版本4.1.2是支持1.7+

**Comment by HeroBarry** [comment]
还是不行&nbsp; Android SDK对代码进行了精简&nbsp; bean相关反射那里没有了&nbsp; &nbsp;我已使用你源码改造&nbsp; 我这已经在Android上可以使用了&nbsp;
