### ISSUE TITLE
[New Feature]可以考虑添加一些可以用来测试的 simple bean

### ISSUE THREAD

**Issue by jiming** [jsonzou/jmockdata#8]
比如

Animal，Cat implements Animal, Dog implements Animal ...

有时候做测试会用到这种 bean，经常需要自己实现。如果加到 jmockdata 里，帮助会很大。

谢谢！

**Comment by jsonzoup** [comment]
你好，有的。在test目录下。

**Comment by jiming** [comment]
两点疑问啊：
1. 在 test 目录下的话别人就无法引用了吧？
2. 感觉那几个bean 有点少，可以多加一些

谢谢！
